# Introdução a Python - Capítulo 6 - NumPy
<br>

**NumPy** é a abreviação de _Numerical Python_ e é um dos pacotes mais importantes para processamento numérico em Python. Esta biblioteca oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com _arrays_ sem a necessidade de utilização de laços `for`;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote **NumPy** também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python. Para saber mais, você pode acessar a [documentação](https://numpy.org/doc/).

---
<br>

### Índice<a id='indice'></a>
1 - [Arrays NumPy](#1)<br>
2 - [Operações aritméticas com arrays NumPy](#2)<br>
3 - [Seleções com arrays NumPy](#3)<br>
4 - [Atributos e métodos de arrays NumPy](#4)<br>
5 - [Estatísticas com arrays Numpy](#5)<br>
<br>

In [1]:
!python --version

Python 3.7.3


## 1. Arrays Numpy<a id='1'></a>
**Obs.**: Eventualmente você irá encontrar apenas o termo _array_ neste capítulo, tenha em mente que se tratam sempre de _arrays_ NumPy.
### 1.1. Arrays unidimensionais
Para começar, vamos usar uma das _built functions_ para criar um _array_ unidimensional, o primeiro passo é importar a biblioteca:

In [2]:
import numpy as np

Usando a função `arange()` podemos criar um _array_ muito facilmente passando apenas um parâmetro

In [3]:
lista1 = np.arange(5)
print(lista1)
print(type(lista1))

[0 1 2 3 4]
<class 'numpy.ndarray'>


Agora vamos utilizar uma das funções da biblioteca NumPy para ler um conjunto de dados de um arquivo externo (txt) e transformar estas informações em _arrays_ NumPy. 

Utilizamos o método [`np.loadtxt()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html?highlight=loadtxt#numpy.loadtxt) para carregar o conteúdo de um arquivo como um _array_ NumPy.

In [4]:
km = np.loadtxt('data/carros-km.txt')

Antes de "printar" o resultado verificamos o tamanho do _array_ com o método [`size`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.size.html):

In [5]:
print(km.dtype)
print(km.size)

float64
258


Sabendo que se trata de um número grande de valores para "printar" na tela, vamos apresentar apenas os dez primeiros:

In [6]:
km[:10]

array([44410.,  5712., 37123.,     0., 25757., 10728.,     0., 77599.,
       99197., 37978.])

Este arquivo que foi importado possui como conteúdo a quilometragem de carros.

Agora vamos importar o arquivo que contém o ano de fabricação de cada um desses carros. Mas agora vamos especificar o tipo de dados dos valores contidos no arquivo, isso é feito passando um segundo parâmetro para o método.

In [7]:
anos = np.loadtxt('data/carros-anos.txt', dtype=int)

In [8]:
print(anos.dtype)
print(anos.size)
print(anos[:10])

int32
258
[2003 1991 1990 2019 2006 2012 2019 2009 2010 2011]


Por fim, vamos calcular a quilometragem média que cada carrou andou por ano. Faremos isso para duas situações: até o ano de 2019 (ano de fabricação mais recente) e o atual. Então, começando por 2020:
<a id='oper_arrays'></a>

In [9]:
km_media_20 = km / (2020 - anos)

In [10]:
km_media_20[:10]

array([2612.35294118,  196.96551724, 1237.43333333,    0.        ,
       1839.78571429, 1341.        ,    0.        , 7054.45454545,
       9919.7       , 4219.77777778])

In [11]:
km_media_19 = km / (2019 - anos)

C:\Users\cesar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [12]:
km_media_19[:10]

array([ 2775.625     ,   204.        ,  1280.10344828,            nan,
        1981.30769231,  1532.57142857,            nan,  7759.9       ,
       11021.88888889,  4747.25      ])

Note que quando calculamos em relação ao ano de 2020 não recebemos nenhum <font color=red>warning</font>, enquanto que para 2019 recebemos um mensagem. Isso se deve a divisões por zero que aconteceram na segunda situação, pois alguns carros foram fabricados em 2019. Perceba que os respectivos elementos no _array_ de quilometragem média receberam o valor `nan` (not a number).

<p style="text-align: right"> <a href="#indice">voltar ao topo </p>

### 1.2. Arrays com duas dimensões
Arrays dimensionais... Observe a lista abaixo que foi atribuida a variável `dados`:

In [13]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]

In [14]:
print(len(dados))
for lista in dados:
    print('lista: {}'.format(lista))

3
lista: ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
lista: ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']
lista: ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


Vamos criar um _array_ multidimensional a partir desta "lista de listas" que armazenamos na variável `dados`:

In [15]:
acessorios = np.array(dados)

Podemos até ver a dimensão deste _array_ com o método `shape`, que retorna uma tuplno seguinte formato: `(linhas, colunas)`

In [16]:
print(km.shape)
print(acessorios.shape)

(258,)
(3, 8)


<p style="text-align: right"> <a href="#indice">voltar ao topo </p>

### 1.3. Comparando desempenho

Vamos avaliar o tempo de execução de iteração sobre esses dois tipos de dados: _arrays_ NumPy e listas. Para isso vamos usar o `%time`, que é uma _built function_ que retorna o tempo utilizado para executar um código.

Então criamos dois iteráveis (uma lista e um _array_ NumPy) de mesmo tamanho e rodamos um `for` para repetir uma ação por 100 vezes, esta ação no caso é multiplicar cada elemento do iterável por 2.

In [17]:
np_array = np.arange(1000000)

In [18]:
%time for _ in list(range(100)): np_array *= 2

Wall time: 125 ms


In [19]:
py_list = list(range(1000000))

In [20]:
%time for _ in list(range(100)): py_list = [x * 2 for x in py_list]

Wall time: 21.5 s


Note que utilizando um _array_ NumPy foi possível executar a ação quase 200 vezes mais rápido.

<p style="text-align: right"> <a href="#indice">voltar ao topo </p>

## 2. Operações aritméticas com arrays NumPy<a id='2'></a>
### 2.1. Operações entre arrays e constantes
Vamos determinar a idade dos carros abaixo a partir do ano de fabricação que está armazenado em uma lista e em um _array_ NumPy.

In [21]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [22]:
idade = 2019 - anos

TypeError: unsupported operand type(s) for -: 'int' and 'list'

Quando tentamos realizar uma operação aritmética entre um inteiro e uma lista, recebemos um aviso de erro dizendo que esta operação não é suportada. Para que isso seja possível com uma lista, devemos utilizar um laço `for` para realizar a operação do inteiro com cada item da lista.

Vamos novamente tentar fazer isso, mas agora a operação será entre um _array_ e um inteiro.

In [23]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [24]:
idade = 2019 - anos
print(idade)

[16 28 29  0 13]


### 2.2. Operações com arrays de duas dimensões
Como já foi visto no [incício](#oper_arrays) deste guia, podemos realizar operações entre dois (ou mais) _arrays_. Além disso podemos realizar operações em _arrays_ multidimensionais. Vamos criar um _array_ de duas dimensões usando os últimos _arrays_ criados:

In [25]:
dados = np.array([km, anos])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [26]:
dados.shape

(2, 5)

Vemos que se trata de uma matriz com duas linhas e cinco colunas, em que a primeira linha representa a quilometragem rodada e a segunda o ano de fabricação. Na imagem abaixo é possível ver a representação dos índices de cada elemento da matriz.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

Novamente vamos calcular a quilometragem média, mas agora usando as linhas da matriz:

In [27]:
km_media = dados[0] / (2019 - dados[1])
km_media

C:\Users\cesar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

<p style="text-align: right"> <a href="#indice">voltar ao topo </p>

## 3. Seleções com arrays Numpy<a id='3'></a>
Para selecionar um elemento específico de um _array_ multidimensional basta seguir a sintaxe abaixo e ir passando o índice de cada "*subarray*":

`ndarray[ linha ][ coluna ]` ou `ndarray[ linha, coluna ]`

In [28]:
dados[1][2]

1990.0

In [29]:
dados[1,2]

1990.0

### 3.1. Fatiamentos
 
A sintaxe para realizar fatiamento em um _array_ NumPy é $i : j : k$ onde $i$ é o índice inicial, $j$ é o índice de parada, e $k$ é o indicador de passo ($k\neq0$). Note que nos fatiamentos, o item com índice $i$ é **incluído** e o item com índice $j$ **não é incluído** no resultado.

Vamos começar experimentando com um _array_ unidimensional:

In [30]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
contador[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
contador[1:8:2]

array([1, 3, 5, 7])

In [33]:
#pegando apenas os números pares
contador[::2]

array([0, 2, 4, 6, 8])

In [34]:
#pegando apenas os números impares
contador[1::2]

array([1, 3, 5, 7, 9])

Agora vamos testar com nosso _array_ bidimensional, calculando a quilometragem média apenas para alguns carros. Basta seguir a síntaxe de seleção multidimensional passando o fatiamento desejado para cada dimensão:

`ndarray[ slice line ][ slice column ]` ou `ndarray[ slice line, slice column ]`

In [35]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [36]:
# seleciono as duas linhas e as colunas de índice 1 e 2
dados[:, 1:3]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [37]:
km_media = dados[:, 1:3][0] / (2019 - dados[:, 1:3][1])
km_media

array([ 204.        , 1280.10344828])

<p style="text-align: right"> <a href="#indice">voltar ao topo </p>

### 3.2. Indexação com array booleano

É possível selecionar um grupo de linhas e colunas segundo os rótulos ou um _array_ booleano. Vontando ao nosso _array_ de exemplo, vamos selecionar apenas os elementos maiores que `5`:

In [38]:
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [40]:
contador[contador > 5]

array([6, 7, 8, 9])

Agora vamos calcular novamente a quilometragem média, mas apenas para carros fabricados depois do ano `2000` **e** que possuem quilometragem maior que `zero`:

In [41]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [42]:
# tentativa de selecionar todas as linhas e (nas colunas) combinar condições que envolvem as duas linhas
dados[:, dados[0] > 0 or dados[1] > 2000]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Aparentemente, não é possível definir uma condição para o fatiamento das colunas que seja uma combinação de condições para cada linha. Portanto, devemos fazer cada fatiamento em separado:

In [43]:
# seleciono todas as linhas e colunas em que a quilometragem é maior que zero
dados = dados[:, dados[0] > 0]
dados

array([[44410.,  5712., 37123., 25757.],
       [ 2003.,  1991.,  1990.,  2006.]])

In [44]:
# seleciono todas as linhas e colunas em que o ano de fabricação é maior que 2000
dados = dados[:, dados[1] > 2000]
dados

array([[44410., 25757.],
       [ 2003.,  2006.]])

In [45]:
km_media = dados[0] / (2019 - dados[1])
km_media

array([2775.625     , 1981.30769231])

E por fim, calculamos a quilometragem média apenas para os veículos fabricados depois do ano 2000 e que possuem quilometragem:

In [46]:
km_media = dados[0] / (2019 - dados[1])
km_media

array([2775.625     , 1981.30769231])

<p style="text-align: right"> <a href="#indice">voltar ao topo </p>

## 4. Atributos e métodos de arrays NumPy<a id='4'></a>
Os _arrays_ NumPy possuem uma série de atributos e métodos muito úteis, você pode acessar as respectivas documentações de [atributos](https://numpy.org/doc/1.17/reference/arrays.ndarray.html#array-attributes) e [métodos](https://numpy.org/doc/1.17/reference/arrays.ndarray.html#array-methods) para obter maiores detalhes. Vamos passar por alguns dos mais comuns.

In [47]:
dados = np.array([km, anos])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

### 4.1. `ndarray.shape`
Retorna uma tupla com as dimensões do array.

In [48]:
dados.shape

(2, 5)

In [49]:
dados_3d = np.array([[km, anos], [km, anos]])
dados_3d

array([[[44410.,  5712., 37123.,     0., 25757.],
        [ 2003.,  1991.,  1990.,  2019.,  2006.]],

       [[44410.,  5712., 37123.,     0., 25757.],
        [ 2003.,  1991.,  1990.,  2019.,  2006.]]])

In [50]:
dados_3d.shape

(2, 2, 5)

### 4.2. `ndarray.ndim`
Retorna o número de dimensões do array.

In [51]:
dados.ndim

2

In [52]:
dados_3d.ndim

3

### 4.3. `ndarray.size`
Retorna o número de elementos do array.

In [53]:
dados.size

10

In [54]:
dados_3d.size

20

<p style="text-align: right"> <a href="#indice">voltar ao topo </p>

### 4.4. `ndarray.dtype`
Retorna o tipo de dados dos elementos do array.

In [55]:
dados.dtype

dtype('float64')

### 4.5. `ndarray.T`
Retorna o array transposto, isto é, converte linhas em colunas e vice versa. É equivalente ao método `transpose()`.

In [56]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [57]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [58]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

### 4.6. `ndarray.tolist()`
Retorna o array como uma lista Python.

In [59]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

<p style="text-align: right"> <a href="#indice">voltar ao topo </p>

### 4.7. `ndarray.reshape(shape[, order])`
Retorna um _array_ que contém os mesmos dados com uma nova forma.

In [60]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

Note que a nova forma deve ser capaz de conter todos os elementos originais:

In [62]:
contador.reshape((3,3))

ValueError: cannot reshape array of size 10 into shape (3,3)

In [63]:
contador.reshape((3,4))

ValueError: cannot reshape array of size 10 into shape (3,4)

<p style="text-align: right"> <a href="#indice">voltar ao topo </p>

#### 4.7.1. Indexação
Por padrao, a indexação utilizada é a da linguagem C, mas podem ser usadas outras, como por exemplo a do Fortran:

In [64]:
contador.reshape((5,2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [65]:
contador.reshape((5,2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

Vamos utilizar um exemplo para verificar a utilidade deste método. Partindo de duas listas que contém a quilometragem e o ano de fabricação de cinco carros. Vamos concatenar as duas listas, transformar a resultante em um _array_ e alterar sua forma.

In [66]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

Vamos alterar a forma do _array_ unidimensional para um bidimensional de 2 linhas e cinco colunas, com a primeira linha contendo a quilometragem e a segunda os anos de fabricação:

In [67]:
np.array(info_carros).reshape((2,5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

Mas também podemos mudar a forma para auma matriz de 5 linhas e 2 colunas, assim, ao invés de termos cada carro representado por uma coluna, teremos um carro por linha. Para isso basta alterar o tipo de indexação:

In [68]:
np.array(info_carros).reshape((5,2), order='F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

### 4.8. `ndarray.resize(new_shape[, refcheck])`
Altera a forma e o tamanho do array.

Já sabemos que para fazer uma cópia de um _array_ não basta apenas atribuir este _array_ a uma variável, dessa forma estamos apenas passando a referência a este _array_. Mas mesmo quando fazemos a cópia de um _array_ usando o método `copy()`, ainda existe uma refência entre os dois _arrays_.

Podemos verificar este comportamento usando o método `resize()`.

In [69]:
new_dados = dados.copy()
new_dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [70]:
new_dados.resize((3,5))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

Perceba que quando tentamos aumentar o tamanho do _array_ obtemos um erro, pois não foi especifícado que a referência ao _array_ original devia ser ignorada.

In [71]:
new_dados.resize((3,5), refcheck=False)
new_dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

Agora que aumentamos o tamanho, adicionando uma linha, podemos colocar a quilometragem média nesta nova linha.  
Obs.: É apresentada a matriz transposta apenas por fins estéticos.

In [72]:
new_dados[2] = new_dados[0] / (2019 - new_dados[1])
new_dados.T

C:\Users\cesar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[44410.        ,  2003.        ,  2775.625     ],
       [ 5712.        ,  1991.        ,   204.        ],
       [37123.        ,  1990.        ,  1280.10344828],
       [    0.        ,  2019.        ,            nan],
       [25757.        ,  2006.        ,  1981.30769231]])

<p style="text-align: right"> <a href="#indice">voltar ao topo </p>

## 5. Estatísticas com arrays Numpy<a id='5'></a>

Agora vamos explorar alguns métodos utilizados para calcular grandezas estatísticas. Vamos passar apenas pelos mais comuns, caso você queira conhecer outros métodos para cálculos [estatísticos](https://numpy.org/doc/1.17/reference/routines.statistics.html) e [matemáticos](https://numpy.org/doc/1.17/reference/routines.math.html), pode acessar a documentação.

Vamos começar carregando três arquivos para _arrays_ NumPy.

In [73]:
anos = np.loadtxt(fname='data/carros-anos.txt', dtype = int)
km = np.loadtxt(fname='data/carros-km.txt')
valor = np.loadtxt(fname='data/carros-valor.txt')

In [74]:
print(anos.shape)
print(km.shape)
print(valor.shape)

(258,)
(258,)
(258,)


Podemos ver os três _arrays_ são unidimensionais, portanto, vamos juntá-los em apenas um. Para isso vamos usar o método [`column_stack()`](https://numpy.org/doc/1.17/reference/generated/numpy.column_stack.html) que coloca cada _array_ como uma coluna do novo _array_.

In [75]:
dataset = np.column_stack((anos, km, valor))
dataset[:10]

array([[  2003.  ,  44410.  ,  88078.64],
       [  1991.  ,   5712.  , 106161.94],
       [  1990.  ,  37123.  ,  72832.16],
       [  2019.  ,      0.  , 124549.07],
       [  2006.  ,  25757.  ,  92612.1 ],
       [  2012.  ,  10728.  ,  97497.73],
       [  2019.  ,      0.  ,  56445.2 ],
       [  2009.  ,  77599.  , 112310.44],
       [  2010.  ,  99197.  , 120716.27],
       [  2011.  ,  37978.  ,  76566.49]])

In [76]:
dataset.shape

(258, 3)

### 5.1. `np.mean()`

Retorna a média dos elementos do array ao longo do eixo especificado.

Se o eixo não for especificado, o método vai simplesmente retornar a média de todos os elementos do _array_. Você pode obter mais [informações](https://numpy.org/doc/1.17/reference/arrays.ndarray.html#calculation) sobre o argumento `axis` na documentação.

In [77]:
# calcula a média de todas as colunas, ou seja, ao longo do eixo vertical
np.mean(dataset, axis=0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

Considerando que não faz sentido calcular a média do ano de fabricação, podemos excluir esta coluna do cálculo. Fazendo um fatiamento no _array_ `dataset` para obter todas as linhas e retirar a primeira coluna:

In [78]:
np.mean(dataset[:, 1:], axis=0)

array([44499.41472868, 98960.51310078])

### 5.2. `np.std()`

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

In [79]:
# calcula apenas para o valor dos carros
np.mean(dataset[:, 2], axis=0)

98960.51310077519

### 5.3. `ndarray.sum()`

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [80]:
dataset.sum(axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [81]:
# calcula a quilometragem rodada por todos os carros
dataset[:,1].sum()

11480849.0

### 5.3. `np.sum()`

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [82]:
np.sum(dataset, axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [83]:
# calcula o valor total de todos os carros
np.sum(dataset[:,2])

25531812.38

<p style="text-align: right"> <a href="#indice">voltar ao topo </p>